The constant is called SHORTINIT, not SHORT_INIT
wp-core-bootstrap/documentation pull request #1
Opened 2017-06-16 10:01 UTC by mwidmann

2017-06-16 10:02 UTC, mwidmann commented
Great talk at #wpeu btw. 👍

2017-06-23 07:25 UTC, schlessera requested changes
There's some bit of random text included in the PR, probably a mistyped search request.

Please remove this artifact, so that I can merge the PR.

2017-06-23 07:25 UTC, schlessera commented on a-constants-reference.md
> +Fshort_
This looks like a search artifact...

2017-06-23 07:32 UTC, mwidmann commented
I removed the additional text, no idea how that came to be.

2017-06-23 07:44 UTC, schlessera approved these changes

2017-06-23 07:45 UTC, merged

2017-06-23 07:45 UTC, schlessera commented
Thanks for the PR, @mwidmann !